spring:
 datasource:
#  url: jdbc:h2:mem:testdb
#  url: jdbc:h2:file:./data/employeedb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=FALSE
   url: jdbc:mysql://localhost:3306/employeedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
   username: springuser
   password: springpass
   driver-class-name: com.mysql.cj.jdbc.Driver #org.h2.Driver
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
 h2:
  console:
   enabled: true
#   path: /h2-console
 logging:
  level:
   root: INFO
   example.coding.practice: DEBUG